# Generated by Django 2.2.6 on 2019-11-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_text', models.CharField(max_length=20)),
                ('tele_text', models.CharField(max_length=20)),
                ('email_text', models.EmailField(max_length=50)),
                ('passeport_text', models.CharField(max_length=200)),
                ('nom_text', models.CharField(max_length=200)),
                ('startprocess_date', models.DateTimeField(verbose_name='processdata')),
                ('endprocess_date', models.DateTimeField(verbose_name='endprocessdata')),
                ('state_int', models.IntegerField()),
                ('notifytele_text', models.CharField(max_length=20)),
            ],
        ),
    ]
