# Generated by Django 2.2.6 on 2019-11-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='nom_text',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='passeport_text',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
